//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightsOutCube.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LightsOutCube.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon MainIcon {
            get {
                object obj = ResourceManager.GetObject("MainIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;XML&gt;
        ///&lt;PUZZLE&gt;
        ///	&lt;L&gt;2&lt;/L&gt;&lt;L&gt;4&lt;/L&gt;&lt;L&gt;5&lt;/L&gt;&lt;L&gt;6&lt;/L&gt;&lt;L&gt;8&lt;/L&gt;
        ///&lt;/PUZZLE&gt;
        ///&lt;PUZZLE&gt;
        ///	&lt;L&gt;1&lt;/L&gt;&lt;L&gt;4&lt;/L&gt;&lt;L&gt;5&lt;/L&gt;&lt;L&gt;7&lt;/L&gt;&lt;L&gt;56&lt;/L&gt;
        ///&lt;/PUZZLE&gt;
        ///&lt;PUZZLE&gt;
        ///	&lt;L&gt;26&lt;/L&gt;&lt;L&gt;28&lt;/L&gt;&lt;L&gt;29&lt;/L&gt;&lt;L&gt;41&lt;/L&gt;&lt;L&gt;33&lt;/L&gt;
        ///&lt;/PUZZLE&gt;
        ///&lt;PUZZLE&gt;
        ///	&lt;L&gt;51&lt;/L&gt;&lt;L&gt;52&lt;/L&gt;&lt;L&gt;56&lt;/L&gt;&lt;L&gt;57&lt;/L&gt;&lt;L&gt;58&lt;/L&gt;&lt;L&gt;38&lt;/L&gt;
        ///&lt;/PUZZLE&gt;
        ///&lt;PUZZLE&gt;
        ///	&lt;L&gt;54&lt;/L&gt;&lt;L&gt;58&lt;/L&gt;&lt;L&gt;34&lt;/L&gt;&lt;L&gt;38&lt;/L&gt;
        ///&lt;/PUZZLE&gt;
        ///&lt;PUZZLE&gt;
        ///	&lt;L&gt;6&lt;/L&gt;&lt;L&gt;16&lt;/L&gt;&lt;L&gt;22&lt;/L&gt;&lt;L&gt;23&lt;/L&gt;&lt;L&gt;24&lt;/L&gt;&lt;L&gt;27&lt;/L&gt;
        ///&lt;/PUZZLE&gt;
        ///&lt;PUZZLE&gt;
        ///	&lt;L&gt;6&lt;/L&gt;&lt;L&gt;9&lt;/L&gt;&lt;L&gt;21&lt;/L&gt;&lt;L&gt;23&lt;/L&gt;&lt;L&gt;27&lt;/L&gt;&lt;L&gt;13&lt;/L&gt;&lt;L&gt;16&lt;/L&gt;
        ///&lt;/PUZZLE&gt;
        ///&lt;PUZZLE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Puzzle {
            get {
                return ResourceManager.GetString("Puzzle", resourceCulture);
            }
        }
    }
}
